config/routes.rb
Rails.application.routes.draw do
  get 'partida_competidor/new'

  resources :eventos do
    resources :partidas do
      resources :competidores_eventos
    end
  end

  resources :arbitros
  devise_for :users, skip:[:resgistrations]
  resources :competidores
  resources :categorias 
  resources :competicoes
  resources :users
              
  root "competidores#index"
 end

app/controllers/competidores_controller.rb
class CompetidoresController < ApplicationController
  before_action :find_competidor, only: [:show, :edit, :update, :destroy]
  def index
    if params[:categoria].blank?
      @competidor = Competidor.all.order("created_at DESC")
    else
      @categoria_id = Categoria.find_by(nome: params[:categoria]).id
      @competidor = Competidor.where(categoria_id: @categoria_id).order("created_at DESC")
    end    
  end

  def show
    
  end

  def new
    @competidor  = Competidor.new
  end

  def create

    @competidor = Competidor.new(competidor_params)

    if @competidor.save
      redirect_to @competidor, notice: "Competidor criado com sucesso"
    else
      render 'new'
    end
  end

  def update
    if @competidor.update(competidor_params)
      redirect_to @competidor
    else
      render 'edit'
    end
  end

  def destroy
    @competidor.destroy
    redirect_to root_path, notice: "Competidor excluído com sucesso"
  end

  private

  def competidor_params
    params.require(:competidor).permit(:nome, :tempo_de_esporte, :patrocinio, :apoio, :instagram, :foto, :categoria_id)
  end

  def find_competidor
    @competidor = Competidor.find(params[:id])
  end
end

app/helpers/competidores_helper.rb
module CompetidoresHelper
end

app/views/competidores/_form.html.haml
= simple_form_for @competidor, html: { multipart: true } do |f|
  =render 'shared/error_messages', {object: @competidor}
  .panel-body
    = f.input :nome, input_html: { class: 'form-control' }
    = f.input :foto, input_html: { class: 'form-control' }
    = f.input :tempo_de_esporte, input_html: { class: 'form-control' }
    = f.input :patrocinio, input_html: { class: 'form-control' }
    = f.input :apoio, input_html: { class: 'form-control' }
    = f.label :categoria_id, "Categoria"
    = f.collection_select :categoria_id, Categoria.all, :id, :nome, {prompt: "Escolha a categoria"}, {class:'form-control'}
    = f.input :instagram, input_html: { class: 'form-control' }
    
  = f.button :submit, class: "btn btn-primary"

app/views/competidores/edit.html.haml
%h1 Editando o competidor

= render 'form'

app/views/competidores/index.html.haml
- @competidor.each do |competidor|
  %h2= link_to competidor.nome, competidor
= link_to "Novo Competidor", new_competidor_path, class: "btn btn-default"    

app/views/competidores/new.html.haml
%h1 Novo Competidor

= render 'competidores/form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/competidores/show.html.haml
%h1= @competidor.nome 
= image_tag @competidor.foto.url(:medium, class: "competidor_foto")
%p 
  %h3 Categoria:
  %h4= @competidor.categoria.nome 
%p 
  %h3 Tempo de esporte:
  %h4= @competidor.tempo_de_esporte
%p
  -unless @competidor.patrocinio.eql?("")
    %h3 Patrocinios :
    %h4= @competidor.patrocinio
%p
  -unless @competidor.apoio.eql?("")
    %h3 Apoio :
    %h4= @competidor.apoio
%p
  %h3 Instagram:
  %h4= @competidor.instagram

= link_to "Back", root_path, class: "btn btn-default"
= link_to "Edit", edit_competidor_path, class: "btn btn-default"
= link_to "Delete", competidor_path, method: :delete, data: {confirm: "Você tem certeza?"},class: "btn btn-default"