config/routes.rb
Rails.application.routes.draw do
  get 'partida_competidor/new'

  resources :eventos do
    resources :partidas do
      resources :competidores_eventos
    end
  end

  resources :arbitros
  devise_for :users, skip:[:resgistrations]
  resources :competidores
  resources :categorias 
  resources :competicoes
  resources :users
              
  root "competidores#index"
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arbitro.rb
class Arbitro < ApplicationRecord
end

app/models/categoria.rb
class Categoria < ApplicationRecord
  has_many :competidores
end

app/models/competicao.rb
class Competicao < ApplicationRecord
end

app/models/competidor.rb
class Competidor < ApplicationRecord
  has_attached_file :foto, styles: { :medium => "200x200#" }
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/
  belongs_to :categoria
  has_and_belongs_to_many :eventos

  def categoria_nome
    categoria.nome
  end

  def descricao
    "#{nome} - #{categoria_nome}"
  end
end

app/models/competidores_evento.rb
class CompetidoresEvento < ApplicationRecord
  belongs_to :evento
  belongs_to :partida
  belongs_to :competidor

  attr_accessor :categoria_id
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
  validates :nome, :dia, :hora, presence: true

  has_attached_file :imagem, styles: { medium: "500x590>", thumb: "300x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/

  has_many :partidas
  has_and_belongs_to_many :competidores

  def possui_partidas
    try(:partidas).present?
  end
end

app/models/partida.rb
class Partida < ApplicationRecord
  validates :tipo, :tempo, :quantidade_rodadas, presence: true

  belongs_to :evento, class_name: "Evento", foreign_key: "evento_id"

  def to_s
    "#{tipo} - #{tempo}"
  end

  def addEvento=(resource)
    self.evento=resource
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/arbitros_controller.rb
class ArbitrosController < ApplicationController
  before_action :set_arbitro, only: [:show, :edit, :update, :destroy]

  # GET /arbitros
  # GET /arbitros.json
  def index
    @arbitros = Arbitro.all
  end

  # GET /arbitros/1
  # GET /arbitros/1.json
  def show
  end

  # GET /arbitros/new
  def new
    @arbitro = Arbitro.new
  end

  # GET /arbitros/1/edit
  def edit
  end

  # POST /arbitros
  # POST /arbitros.json
  def create
    @arbitro = Arbitro.new(arbitro_params)

    respond_to do |format|
      if @arbitro.save
        format.html { redirect_to @arbitro, notice: 'Arbitro was successfully created.' }
        format.json { render :show, status: :created, location: @arbitro }
      else
        format.html { render :new }
        format.json { render json: @arbitro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arbitros/1
  # PATCH/PUT /arbitros/1.json
  def update
    respond_to do |format|
      if @arbitro.update(arbitro_params)
        format.html { redirect_to @arbitro, notice: 'Arbitro was successfully updated.' }
        format.json { render :show, status: :ok, location: @arbitro }
      else
        format.html { render :edit }
        format.json { render json: @arbitro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arbitros/1
  # DELETE /arbitros/1.json
  def destroy
    @arbitro.destroy
    respond_to do |format|
      format.html { redirect_to arbitros_url, notice: 'Arbitro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arbitro
      @arbitro = Arbitro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arbitro_params
      params.require(:arbitro).permit(:nome)
    end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :find_categoria, only: [:show, :edit, :update, :destroy]
  def index
    @categorias = Categoria.all.order("nome ASC")
  end

  def show
    
  end

  def new
    @categoria = Categoria.new
  end

  def create

    @categoria = Categoria.new(categoria_params)
    if @categoria.save
      redirect_to @categoria, notice: "Categoria criada com sucesso"
    else
      render 'new'
    end
  end

  def update
    if @categoria.update(categoria_params)
      redirect_to @categoria
    else
      render 'edit'
    end
  end

  def destroy
    @categoria.destroy
    redirect_to categorias_path, notice: "Categoria excluída com sucesso"
  end

  private

  def categoria_params
    params.require(:categoria).permit(:nome, :status)
  end

  def find_categoria
     @categoria = Categoria.find(params[:id])
  end 
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  def index
    @eventos = Evento.all
  end

  def show
  end

  def new
    @evento = Evento.new
  end

  def edit
  end

  def create
    @evento = Evento.new(resource_params)
    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @evento.update(resource_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_evento
      @evento = Evento.find(params[:id])
    end

    def resource_params
      params.require(:evento).permit(:nome, :dia, :hora, :imagem, partidas_attributes:[:evento_id, :tipo, :tempo, :quantidade_rodadas, :_destroy])
    end
end

app/controllers/partidas_controller.rb
class PartidasController < ApplicationController
  before_action :find_evento

  def new
    @partida = Partida.new
    respond_to &:js
  end

  def create
    @partida=Partida.new(resource_params)
    @partida.addEvento=@evento
    @partida.save
    respond_to &:js
  end

  def start_game
    
  end

  private
    def find_evento
      @evento = Evento.find(params[:evento_id])
    end

    def resource_params
      params.require(:partida).permit(:tipo, :tempo, :quantidade_rodadas, :evento_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_action :find_users, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all.order("created_at DESC")
  end

  def show
    
  end

  def new
    @user = User.new
  end

  def create
    @user  = User.new(users_params)

    if @user.save
      redirect_to @user, notice: "Usuário criado com sucesso"
    else
      render 'new'
    end
  end

  def update
    if @user.update(users_params)
      redirect_to @user

    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: "Usuário excluído com sucesso"
  end

  private

  def users_params
    params.require(:user).permit(:nome, :password, :administrador)
  end

  def find_users
    @user  = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime("%d/%m/%Y")
  end

  def format_hour(hour)
    hour.strftime("%H:%M")
  end
end

app/helpers/arbitros_helper.rb
module ArbitrosHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/competidores_helper.rb
module CompetidoresHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/partida_competidor_helper.rb
module PartidaCompetidorHelper
end

app/helpers/partidas_helper.rb
module PartidasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/arbitros/_form.html.haml
= simple_form_for @arbitro do |f|
  =render 'shared/error_messages', {object: @arbitro}
  .row
    .col-md-4
      = f.input :nome
  .row
    .col-md-12
      .pull-left
        = f.submit 'Criar', class: "btn btn-primary"
      .pull-right
        = link_to "Pagina inicial", root_path, class: "btn btn-default"

app/views/arbitros/edit.html.haml
%h1 Editing arbitro

= render 'form'

= link_to 'Show', @arbitro
\|
= link_to 'Back', arbitros_path

app/views/arbitros/index.html.haml
- @arbitros.each do |arbitro|
  %h2= link_to arbitro.nome, arbitro
= link_to "Novo arbitro", new_arbitro_path, class: "btn btn-default"

app/views/arbitros/new.html.haml
.container
  %h1 Novo arbitro
  = render 'form'

%br/

app/views/arbitros/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @arbitro.nome

= link_to 'Edit', edit_arbitro_path(@arbitro)
\|
= link_to 'Back', arbitros_path

app/views/categorias/_form.html.haml
= simple_form_for @categoria, html: { multipart: true } do |f|
  =render 'shared/error_messages', {object: @categoria}
  .panel-body
    = f.input :nome, input_html: { class: 'form-control' }
   
    
  = f.button :submit, class: "btn btn-primary"

app/views/categorias/edit.html.haml
%h1 Editando a categoria

= render 'form'

app/views/categorias/index.html.haml
- @categorias.each do |categoria|
  %h2= link_to categoria.nome, categoria
= link_to "Nova Categoria", new_categoria_path, class: "btn btn-default"  

app/views/categorias/new.html.haml
%h1 Nova Categoria

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/categorias/show.html.haml
%h1= @categoria.nome 


= link_to "Back", categorias_path, class: "btn btn-default"
= link_to "Edit", edit_categoria_path, class: "btn btn-default"
= link_to "Delete", categoria_path, method: :delete, data: {confirm: "Você tem certeza?"},class: "btn btn-default"

app/views/eventos/_competidores.html.haml
.col-md-6
  #directions
    %h2 Competidores
    %ul
      -evento.competidores.each do |competidor|
        %li
          %strong=competidor.descricao

app/views/eventos/_evento.html.haml
.main_content
  #event_top.row
    .col-md-6
      = image_tag @evento.imagem.url(:medium), class: "event_image"
    .col-md-6
      #event_info
        %h1= @evento.nome
        .row
          .col-md-4
            %p
              %h3 Dia
              =format_date @evento.dia
          .col-md-4
            %p
              %h3 Horario
              =format_hour @evento.hora
        .row
          -if current_page?(evento_path(@evento))
            =link_to "Editar Evento", edit_evento_path(@evento), class: "btn btn-default"
            =link_to "Adicionar Partidas", new_evento_partida_path(@evento), class: "btn btn-default", remote: true, id: "btnNewGame"

app/views/eventos/_form.html.haml
= simple_form_for @evento, html: { multipart: true } do |f|
  =render 'shared/error_messages', {object: @evento}
  .panel.panel-default
    .panel-body
      = f.input :nome, input_html: { class: 'form-control' }
      = f.input :dia, input_html: { class: 'form-control' }
      = f.input :hora, input_html: { class: 'form-control' }
      = f.input :imagem, as: :file
  = f.button :submit, class: "btn btn-primary"

app/views/eventos/_partida_fields.html.haml
.form-inline.clearfix
  .nested-fields
    .col-md-3
      = f.label :tipo
      = f.input :tipo, label: false, input_html: { class: 'form-input form-control' }
    .col-md-3
      = f.label :tempo
      = f.input :tempo, label: false, input_html: { class: 'form-input form-control' }
    .col-md-3
      = f.label :quantidade
      = f.input :quantidade_rodadas, label: false, input_html: { class: 'form-input form-control' }
    .col-md-3
      = link_to_remove_association "Remove", f, class: "btn btn-default"

app/views/eventos/_partidas.html.haml
.col-md-6
  #partidas
    %h2 Partidas
    %ul
      - evento.partidas.each do |partida|
        %li
          .col-md-4
            %h4= partida.to_s
          .col-md-4
            =link_to new_evento_partida_competidores_evento_path(evento, partida), class: "btn btn-primary", title: "Adicionar Competidores" do
              %i.mdi.mdi-account
            =link_to new_evento_partida_competidores_evento_path(evento, partida), class: "btn btn-warning", title: "Iniciar Partida" do
              %i.mdi.mdi-alarm
              
        %br

app/views/eventos/edit.html.haml
%h1 Editing evento

= render 'form'

= link_to 'Show', @evento
\|
= link_to 'Back', eventos_path

app/views/eventos/index.html.haml
- @eventos.each do |evento|
  %h2= link_to evento.nome, evento
= link_to "Novo Evento", new_evento_path, class: "btn btn-default"  

app/views/eventos/new.html.haml
%h1 Novo Evento

= render 'form'

= link_to 'Voltar', eventos_path

app/views/eventos/show.html.haml
=render 'evento'

.row
  #evento_partidas
    -if @evento.possui_partidas
      =render 'partidas', { evento: @evento }
  #evento_competidores
    =render 'competidores', { evento: @evento }
#NewGame

app/views/partidas/_new.html.haml
/ Modal
=simple_form_for [@evento, @partida], method: "POST", remote: true do |t|
  #ModalNewGame.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#myModalLabel.modal-title Nova Partida
        .modal-body
          = t.input  :tipo
          = t.input  :tempo
          = t.input :quantidade_rodadas
        .modal-footer
          =t.submit "Enviar", class: "btn btn-default"
          %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Fechar

app/views/partidas/create.js.erb
$("#ModalNewGame.modal").modal('hide')
$("#NewGame").empty()
$("#evento_partidas").append("<%=j render 'eventos/partidas', {evento: @evento} %>")

app/views/partidas/new.js.erb
$("#NewGame").empty()
$("#NewGame").append("<%=j render('new')%>")
$("#ModalNewGame.modal").modal('show')

app/views/users/edit.html.erb
<h2>Sign up</h2>

<%= simple_form_for(@user, url: user_path, method: 'put') do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome, required: true, autofocus: true %>
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>
    <%= f.label "Administrador"%>
    <%= f.check_box :administrador%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= simple_form_for(@user, url: users_path, method: 'post') do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome, required: true, autofocus: true %>
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>
    <%= f.label "Administrador"%>
    <%= f.check_box :administrador%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>